import ExcelJS from "exceljs";

const BRAND_ORANGE = "FFFE9F43";
const HEADER_TEXT = "FFFFFFFF";
const ZEBRA = "FFFAFBFE";

interface ExcelReportInput {
  /** Worksheet name + subtitle label — cosmetic only, any short title works
   * (not constrained to the formal Reports feature's ReportType union). */
  type: string;
  from: string;
  to: string;
  headers: string[];
  rows: string[][];
  summary: string;
  generatedBy: string;
  companyName: string;
  warehouseLocation: string;
}

/** Builds a branded single-sheet workbook mirroring the PDF report layout. */
export async function generateExcelReport(input: ExcelReportInput): Promise<Buffer> {
  const workbook = new ExcelJS.Workbook();
  workbook.creator = input.companyName;
  workbook.created = new Date();

  const sheet = workbook.addWorksheet(input.type, {
    properties: { defaultRowHeight: 18 },
  });
  const columnCount = Math.max(input.headers.length, 1);

  sheet.mergeCells(1, 1, 1, columnCount);
  const titleCell = sheet.getCell(1, 1);
  titleCell.value = input.companyName;
  titleCell.font = { bold: true, size: 14 };

  sheet.mergeCells(2, 1, 2, columnCount);
  sheet.getCell(2, 1).value = `${input.type} — ${input.from} to ${input.to}`;
  sheet.getCell(2, 1).font = { size: 11 };

  sheet.mergeCells(3, 1, 3, columnCount);
  sheet.getCell(3, 1).value =
    `${input.summary} · Generated by ${input.generatedBy} · ${input.warehouseLocation}`;
  sheet.getCell(3, 1).font = { size: 9, color: { argb: "FF646B72" } };

  const headerRow = sheet.getRow(5);
  input.headers.forEach((header, i) => {
    const cell = headerRow.getCell(i + 1);
    cell.value = header;
    cell.font = { bold: true, color: { argb: HEADER_TEXT } };
    cell.fill = { type: "pattern", pattern: "solid", fgColor: { argb: BRAND_ORANGE } };
    cell.alignment = { vertical: "middle" };
  });
  headerRow.height = 22;

  input.rows.forEach((row, rowIndex) => {
    const excelRow = sheet.getRow(6 + rowIndex);
    row.forEach((value, colIndex) => {
      const cell = excelRow.getCell(colIndex + 1);
      const numeric = value !== "" && !Number.isNaN(Number(value));
      cell.value = numeric ? Number(value) : value;
      if (rowIndex % 2 === 1) {
        cell.fill = { type: "pattern", pattern: "solid", fgColor: { argb: ZEBRA } };
      }
    });
  });

  for (let c = 0; c < columnCount; c++) {
    const lengths = [
      input.headers[c]?.length ?? 0,
      ...input.rows.map((r) => String(r[c] ?? "").length),
    ];
    sheet.getColumn(c + 1).width = Math.min(50, Math.max(12, Math.max(...lengths) + 2));
  }

  const arrayBuffer = await workbook.xlsx.writeBuffer();
  return Buffer.from(arrayBuffer);
}
