export const queryKeys = {
  dashboard: ["dashboard"] as const,
  inventory: (params: { q?: string; category?: string; page?: number }) =>
    ["inventory", params] as const,
  products: (params: { page?: number }) => ["products", params] as const,
  suppliers: (params: { page?: number }) => ["suppliers", params] as const,
  technicians: (params: { page?: number }) => ["technicians", params] as const,
  users: (params: { page?: number }) => ["users", params] as const,
  userHistory: (userId: string) => ["users", userId, "history"] as const,
  activity: (params: { page?: number }) => ["activity", params] as const,
  settings: ["settings"] as const,
  profile: ["profile"] as const,
  reports: ["reports"] as const,
  stockIn: (params: { page?: number }) => ["stock-in", params] as const,
  stockOut: (params: { page?: number; q?: string }) => ["stock-out", params] as const,
  stockOptions: ["stock-options"] as const,
  mrf: (params: { page?: number }) => ["mrf", params] as const,
  openMrfs: (params: { page?: number } = {}) => ["mrf-open", params] as const,
  adjustments: (params: { page?: number }) => ["adjustments", params] as const,
  notifications: ["notifications"] as const,
  myPermissions: ["me-permissions"] as const,
  purchaseOrders: (params: { page?: number }) => ["purchase-orders", params] as const,
  purchaseRequests: (params: { page?: number }) => ["purchase-requests", params] as const,
};
